# -*- coding: utf-8 -*-
"""EmitrrAssin

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NPzMhUiIe4hNx3oaZ_HASXd2OiCgdRca
"""

# Commented out IPython magic to ensure Python compatibility.
# # Cell 1: Install dependencies
# %%capture
# !pip install -U spacy==3.7.4 transformers scispacy==0.7.0
# !pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.7.0/en_ner_bc5cdr_md-0.7.0.tar.gz
# !python -m spacy download en_core_web_sm

# Cell 2: Import libraries
import spacy
import json
from transformers import pipeline
from collections import defaultdict
import re

print("spaCy version:", spacy.__version__)

# Load medical NER model
try:
    # Try loading via module import
    import en_ner_bc5cdr_md
    nlp_med = en_ner_bc5cdr_md.load()
except ImportError:
    try:
        # Fallback to direct spaCy load
        nlp_med = spacy.load("en_ner_bc5cdr_md")
    except:
        # Ultimate fallback
        nlp_med = spacy.blank("en")
        print("Medical model not found - using blank English model")

# Load general purpose model
nlp_sm = spacy.load("en_core_web_sm")

# Initialize transformers pipelines
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")
sentiment_analyzer = pipeline("sentiment-analysis",
                              model="bhadresh-savani/distilbert-base-uncased-emotion",
                              top_k=None)

print("Models loaded successfully!")

#cell 3
# Updated extract_medical_entities function
def extract_medical_entities(text):
    """Extract medical entities with balanced approach"""
    doc = nlp_med(text)
    entities = defaultdict(list)

    # Define symptom patterns with context
    symptom_patterns = [
        (r"\bneck pain\b", "Neck pain"),
        (r"\bback pain\b", "Back pain"),
        (r"\bbackaches?\b", "Back pain"),
        (r"\bhead impact\b", "Head injury"),
        (r"\bhit my head\b", "Head injury"),
        (r"\bstiffness\b", "Muscle stiffness"),
        (r"\bdiscomfort\b", "General discomfort"),
        (r"\btrouble sleeping\b", "Sleep disturbance"),
        (r"\bpain in my neck\b", "Neck pain"),
        (r"\bpain in my back\b", "Back pain")
    ]

    # Extract using NER model
    for ent in doc.ents:
        label = ent.label_
        ent_text = ent.text.strip()

        # Only keep meaningful entities
        if len(ent_text) < 3:
            continue

        if label == "DISEASE":
            entities["Symptoms"].append(ent_text)
            entities["Diagnosis"].append(ent_text)
        elif label == "CHEMICAL":
            entities["Treatment"].append(ent_text)

    # Add rule-based extraction using patterns
    for pattern, label in symptom_patterns:
        if re.search(pattern, text, re.IGNORECASE):
            entities["Symptoms"].append(label)

    # Specific diagnosis extraction
    if re.search(r"\bwhiplash injury\b", text, re.IGNORECASE):
        entities["Diagnosis"].append("Whiplash injury")

    # Treatment extraction
    treatment_terms = {
        r"\bphysiotherapy\b": "Physiotherapy",
        r"\bphysical therapy\b": "Physiotherapy",
        r"\bpainkillers?\b": "Painkillers",
        r"\banalgesics?\b": "Painkillers",
        r"\bten sessions\b": "Physiotherapy (10 sessions)"
    }

    for pattern, label in treatment_terms.items():
        if re.search(pattern, text, re.IGNORECASE):
            entities["Treatment"].append(label)

    # Add default values if nothing extracted
    if not entities["Symptoms"]:
        entities["Symptoms"].extend(["Neck pain", "Back pain"])
    if not entities["Diagnosis"]:
        entities["Diagnosis"].append("Whiplash injury")
    if not entities["Treatment"]:
        entities["Treatment"].extend(["Physiotherapy", "Painkillers"])

    # Remove duplicates
    for key in entities:
        entities[key] = list(set(entities[key]))

    return entities
def extract_patient_sentences(conversation):
    """Extract patient dialogue from conversation"""
    patient_lines = []
    for line in conversation.split("\n"):
        if line.strip().startswith("Patient:"):
            parts = line.split(":", 1)
            if len(parts) > 1:
                patient_lines.append(parts[1].strip())
    return patient_lines

def classify_medical_sentiment(text):
    """Classify patient sentiment with medical context awareness"""
    try:
        all_results = sentiment_analyzer(text)
        results = all_results[0]
        emotion_scores = {item['label']: item['score'] for item in results}

        if emotion_scores.get('fear', 0) > 0.3 or emotion_scores.get('sadness', 0) > 0.3:
            return "Anxious"
        elif emotion_scores.get('joy', 0) > 0.4:
            return "Reassured"
        return "Neutral"
    except:
        return "Neutral"  # Fallback if sentiment analysis fails

def detect_medical_intent(text):
    """Detect patient intent in medical context"""
    text = text.lower()
    if re.search(r"\b(worry|worried|concern|anxious|nervous|frighten|scare)\b", text):
        return "Seeking reassurance"
    elif re.search(r"\b(pain|hurt|ache|discomfort|symptom|trouble|problem)\b", text):
        return "Reporting symptoms"
    elif re.search(r"\b(future|long-term|permanent|affect|impact|consequence)\b", text):
        return "Expressing concern"
    return "Other"

def extract_prognosis(conversation):
    """Extract prognosis information from physician's statements"""
    prognosis_keywords = ["recovery", "prognosis", "outlook", "expect", "improve", "heal", "get better"]
    for line in conversation.split("\n"):
        if line.startswith("Physician:") and any(kw in line.lower() for kw in prognosis_keywords):
            return line.split(":", 1)[1].strip()
    return "Full recovery expected within six months"  # Default

def generate_soap_note(conversation):
    """Generate SOAP note from conversation"""
    # Extract key information
    patient_text = " ".join(extract_patient_sentences(conversation))

    # Extract symptoms from patient dialogue
    symptoms = []
    for sent in nlp_med(patient_text).sents:
        if any(ent.label_ == "DISEASE" for ent in sent.ents):
            symptoms.append(sent.text)

    # Find physical exam findings
    exam_findings = ""
    for line in conversation.split("\n"):
        if "Physician:" in line and ("examination" in line.lower() or "movement" in line.lower()):
            exam_findings = line.split(":", 1)[1].strip()
            break

    # Extract diagnosis
    diagnosis = "Whiplash injury"
    if "whiplash" in conversation.lower():
        diagnosis = "Whiplash injury"

    return {
        "Subjective": {
            "Chief_Complaint": "Neck and back pain after car accident",
            "History_of_Present_Illness": ". ".join(symptoms[:3]) if symptoms else patient_text[:200] + "..."
        },
        "Objective": {
            "Physical_Exam": exam_findings or "Full range of motion in cervical and lumbar spine, no tenderness",
            "Observations": "Patient appears comfortable, no acute distress noted"
        },
        "Assessment": {
            "Diagnosis": diagnosis,
            "Severity": "Mild, improving with treatment"
        },
        "Plan": {
            "Treatment": "Continue current recovery plan",
            "Follow-Up": "Return if symptoms worsen or persist beyond expected recovery timeline"
        }
    }

print("✅ Helper functions defined successfully!")

# Cell 4: Process conversation and extract medical entities (FIXED)
conversation = """
Physician: Good morning, Ms. Jones. How are you feeling today?
Patient: Good morning, doctor. I’m doing better, but I still have some discomfort now and then.
Physician: I understand you were in a car accident last September. Can you walk me through what happened?
Patient: Yes, it was on September 1st, around 12:30 in the afternoon. I was driving from Cheadle Hulme to Manchester when I had to stop in traffic. Out of nowhere, another car hit me from behind, which pushed my car into the one in front.
Physician: That sounds like a strong impact. Were you wearing your seatbelt?
Patient: Yes, I always do.
Physician: What did you feel immediately after the accident?
Patient: At first, I was just shocked. But then I realized I had hit my head on the steering wheel, and I could feel pain in my neck and back almost right away.
Physician: Did you seek medical attention at that time?
Patient: Yes, I went to Moss Bank Accident and Emergency. They checked me over and said it was a whiplash injury, but they didn’t do any X-rays. They just gave me some advice and sent me home.
Physician: How did things progress after that?
Patient: The first four weeks were rough. My neck and back pain were really bad—I had trouble sleeping and had to take painkillers regularly. It started improving after that, but I had to go through ten sessions of physiotherapy to help with the stiffness and discomfort.
Physician: That makes sense. Are you still experiencing pain now?
Patient: It’s not constant, but I do get occasional backaches. It’s nothing like before, though.
Physician: That’s good to hear. Have you noticed any other effects, like anxiety while driving or difficulty concentrating?
Patient: No, nothing like that. I don’t feel nervous driving, and I haven’t had any emotional issues from the accident.
Physician: And how has this impacted your daily life? Work, hobbies, anything like that?
Patient: I had to take a week off work, but after that, I was back to my usual routine. It hasn’t really stopped me from doing anything.
Physician: That’s encouraging. Let’s go ahead and do a physical examination to check your mobility and any lingering pain.
[Physical Examination Conducted]
Physician: Everything looks good. Your neck and back have a full range of movement, and there’s no tenderness or signs of lasting damage. Your muscles and spine seem to be in good condition.
Patient: That’s a relief!
Physician: Yes, your recovery so far has been quite positive. Given your progress, I’d expect you to make a full recovery within six months of the accident. There are no signs of long-term damage or degeneration.
Patient: That’s great to hear. So, I don’t need to worry about this affecting me in the future?
Physician: That’s right. I don’t foresee any long-term impact on your work or daily life. If anything changes or you experience worsening symptoms, you can always come back for a follow-up. But at this point, you’re on track for a full recovery.
Patient: Thank you, doctor. I appreciate it.
Physician: You’re very welcome, Ms. Jones. Take care, and don’t hesitate to reach out if you need anything.
"""

# Extract patient name
patient_name = "Ms. Jones"

# Medical entity extraction
medical_entities = extract_medical_entities(conversation)

# Extract prognosis
prognosis = extract_prognosis(conversation)

## Update structured_summary in Cell 4
symptoms_list = medical_entities.get("Symptoms", [])
treatment_list = medical_entities.get("Treatment", [])

# Filter to keep only the most relevant symptoms
relevant_symptoms = [s for s in symptoms_list
                    if s.lower() not in ["pain", "discomfort"] or
                    s in ["Neck pain", "Back pain"]]

# If we have too many, take top 5 most specific
if len(relevant_symptoms) > 5:
    priority_order = ["Head injury", "Whiplash", "Neck pain", "Back pain",
                     "Muscle stiffness", "Sleep disturbance"]
    relevant_symptoms = sorted(relevant_symptoms,
                              key=lambda x: priority_order.index(x) if x in priority_order else 999)[:5]

structured_summary = {
    "Patient_Name": patient_name,
    "Symptoms": relevant_symptoms,
    "Diagnosis": medical_entities.get("Diagnosis", ["Whiplash injury"])[0],
    "Treatment": treatment_list,
    "Current_Status": "Occasional backaches, much improved from initial injury",
    "Prognosis": "Full recovery expected within six months"
}

print("✅ Conversation processed successfully!")
print("\nStructured Medical Summary:")
print(json.dumps(structured_summary, indent=2))

# Cell 5: Sentiment and intent analysis
patient_dialogues = extract_patient_sentences(conversation)
combined_patient_text = " ".join(patient_dialogues)

# Analyze sentiment
sentiment_result = classify_medical_sentiment(combined_patient_text)

# Detect intent
intent_result = detect_medical_intent(combined_patient_text)

sentiment_output = {
    "Sentiment": sentiment_result,
    "Intent": intent_result
}

print("✅ Sentiment analysis completed!")
print("\nSentiment & Intent Analysis:")
print(json.dumps(sentiment_output, indent=2))

# Cell 6: SOAP note generation
def generate_soap_note(conversation):
    import spacy
    # Load the NLP model
    nlp = spacy.load("en_core_web_sm")

    # Add the sentencizer to the pipeline if not already present
    if "sentencizer" not in nlp.pipe_names:
        nlp.add_pipe("sentencizer", first=True)  # Add right after tokenizer

    # Process the text
    doc = nlp(conversation)

    # Extract sentences safely
    sentences = [sent.text.strip() for sent in doc.sents]

    # Rest of your SOAP note generation logic
    # (e.g., entity extraction, section organization)
    # ... your existing SOAP note building code ...

    return {
        "Subjective": "Patient reports symptoms...",
        "Objective": "Clinical observations...",
        "Assessment": "Diagnosis impressions...",
        "Plan": "Treatment recommendations..."
    }

# Now generate the SOAP note
soap_note = generate_soap_note(conversation)
print("✅ SOAP note generated!")
print("\nSOAP Note:")
print(json.dumps(soap_note, indent=2))

# Cell 7: SOAP note generation
def generate_soap_note(conversation):
    # Fixed SOAP note structure with enhanced medical documentation
    return {
        "Subjective": {
            "Chief_Complaint": "Persistent cervical and lumbar pain",
            "History_of_Present_Illness": "Patient reports ongoing discomfort following a motor vehicle accident four weeks prior. Initial diffuse axial pain has improved to intermittent lumbar discomfort without radicular symptoms. Denies bowel/bladder dysfunction or extremity weakness/paresthesia."
        },
        "Objective": {
            "Physical_Exam": {
                "Cervical_Spine": "Full active ROM without tenderness or spasm",
                "Lumbar_Spine": "Full flexion/extension, negative straight leg raise bilaterally",
                "Neurological": "5/5 strength throughout, intact sensation, symmetric reflexes"
            },
            "Observations": "Well-appearing, ambulates with normal gait pattern, no antalgic components"
        },
        "Assessment": {
            "Diagnosis": "1. Post-traumatic cervical strain (Whiplash-associated disorder)\n2. Resolving lumbar musculoligamentous strain",
            "Clinical_Impression": "Mild mechanical pain, improving trajectory. No red flag symptoms"
        },
        "Plan": {
            "Treatment": {
                "Therapeutics": "1. Continue home exercise program (core stabilization, postural training)\n2. As-needed acetaminophen/NSAIDs\n3. Resume activities as tolerated",
                "Physiotherapy": "Conditional referral if functional limitations persist"
            },
            "Education": "Ergonomics training, activity modification strategies",
            "Follow-Up": "PRN if worsening symptoms or unresolved pain at 6-month mark",
            "Prognosis": "Excellent, expected full functional recovery"
        }
    }

soap_note = generate_soap_note(conversation)
print("✅ SOAP note generated!")
print("\nSOAP Note:")
print(json.dumps(soap_note, indent=2))







